oro_layout:
    actions:
        - @setBlockTheme:
            themes: 'OroUIBundle:layouts:base/update/default.html.twig'
        - @add:
            id:        update_before_content_addition
            parentId:  before_content_addition
            blockType: placeholder
            options:
                placeholder_name: content_after
                placeholder_parameters:
                    entity: { @value: $data.entity }
        - @addTree:
            items:
                'form:start':
                    blockType: form_start
                form:
                    blockType: form_end
                    options:
                        form_prefix: form
                'form:end':
                    blockType: form_end
                page_header:
                    blockType: container
                page_header_left_panel:
                    blockType: container
                page_header_right_panel:
                    blockType: container
                page_title:
                    blockType: text
                page_buttons_panel:
                    blockType: container
                    options:
                        vars:
                            form_name: { @value: $context.form.name }
                            form_method: { @value: $context.form.method }
                nav_buttons:
                    blockType: container
                update_navButtons_before_placeholder:
                    blockType: placeholder
                    options:
                        placeholder_name: update_navButtons_before
                        placeholder_parameters:
                            entity: { @value: $data.entity }
                update_navButtons_after_placeholder:
                    blockType: placeholder
                    options:
                        placeholder_name: update_navButtons_after
                        placeholder_parameters:
                            entity: { @value: $data.entity }
            tree:
                content:
                    'form:start': ~
                    page_header:
                        page_header_left_panel:
                            page_title: ~
                        page_header_right_panel:
                            page_buttons_panel:
                                update_navButtons_before_placeholder: ~
                                nav_buttons: ~
                                update_navButtons_after_placeholder: ~
                    'form:end': ~
