js:
  - '@OroUIBundle/Resources/public/lib/jquery.min.js'
  - '@OroUIBundle/Resources/public/lib/jquery-ui.min.js'
  - '@OroUIBundle/Resources/public/lib/base64.js'
  - '@OroUIBundle/Resources/public/lib/underscore.js'
  - '@OroUIBundle/Resources/public/lib/backbone.js'
  - '@OroUIBundle/Resources/public/js/backbone/app.js'
  - '@OroUIBundle/Resources/public/js/backbone/app/events.js'
  - '@OroUIBundle/Resources/public/lib/jquery/jquery.mousewheel.min.js'
  - '@OroUIBundle/Resources/public/lib/jquery/jquery.numeric.js'
  - '@OroUIBundle/Resources/public/lib/jquery/jquery.uniform.min.js'
  - '@OroUIBundle/Resources/public/lib/jquery/select2.min.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap.min.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap/js/bootstrap-tooltip.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap/js/bootstrap-popover.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap/js/bootstrap.switch.js'
  - '@OroUIBundle/Resources/public/lib/bootstrap/js/bootstrap-scrollspy.js'

  - '@OroUIBundle/Resources/public/js/layout.js'
  - '@OroUIBundle/Resources/public/js/height_fix.js'
  - '@OroUIBundle/Resources/public/js/csrf.js'
  - '@OroUIBundle/Resources/public/js/backbone/error.js'
  - '@OroUIBundle/Resources/public/js/backbone/message.js'
  - '@OroUIBundle/Resources/public/js/registry.js'

  - '@OroUIBundle/Resources/public/lib/backbone.bootstrap-modal.js'
  - '@OroUIBundle/Resources/public/js/backbone/bootstrap-modal.js'

  - '@OroUIBundle/Resources/public/js/remove.confirm.js'

  - '@OroUIBundle/Resources/public/js/backbone/setup.js'

  - '@FOSJsRoutingBundle/Resources/public/js/router.js'
  - '@BazingaExposeTranslationBundle/Resources/public/js/translator.min.js'
  - 'js/routes.js'
css:
  - 'bundles/oroui/lib/jstree/themes/default/style.css'
  - 'bundles/oroui/css/jquery-ui.grid.css'
