    oro_ui.block_type.datagrid:
        class: Oro\Bundle\UIBundle\Layout\Block\Type\DatagridType
        arguments:
            - @oro_datagrid.datagrid.name_strategy
        tags:
             - { name: layout.block_type, alias: datagrid }

    oro_ui.block_type_extension.taggable_datagrid:
        class: Oro\Bundle\UIBundle\Layout\Block\Extension\TaggableDatagridExtension
        tags:
            - { name: layout.block_type_extension, alias: datagrid }

