placeholders:
    header_logo:
        label: Header Logo
        items:
            logo:
                order: 100
    user_menu:
        label: Profile menu
        items:
            help:
                order: 200
    form_buttons:
        label: Profile menu
        items:
            add_update_delete:
                order: 100

items:
   logo:
        template: OroUIBundle:Default:logo.html.twig
   help:
        template: OroUIBundle:Default:help.html.twig
   add_update_delete:
        template: OroUIBundle:Form:buttons.html.twig
