placeholders:
    header_logo:
        items:
            logo:
                order: 100
    user_menu:
        items:
            help:
                order: 200
    form_buttons:
        items:
            add_update_delete:
                order: 100
    head_style: ~
    head_script: ~
    scripts_after:
        items:
            init_pinned_dropdown_button:
                order: 100

    requirejs_config_extend:
        items:
            ui_requirejs_config:
                order: 10

    view_content_data:
        blocks:
            communications:
                label: Communications
            additional_information:
                label: Additional Information

items:
    logo:
        template: OroUIBundle:Default:logo.html.twig
    help:
        template: OroUIBundle:Default:help.html.twig
    add_update_delete:
        template: OroUIBundle:Form:buttons.html.twig
    ui_requirejs_config:
        template: OroUIBundle::requirejs.config.js.twig
    init_pinned_dropdown_button:
        template: OroUIBundle:Js:init_pinned_dropdown_button.js.twig
