config:
    shim:
        'jquery-ui':
            deps:
                - 'jquery'
        'jquery-ui-timepicker':
            deps:
                - 'jquery-ui'
        'jquery.mousewheel':
            deps:
                - 'jquery'
        'jquery.numeric':
            deps:
                - 'jquery'
        'jquery.uniform':
            deps:
                - 'jquery'
        'jquery.select2':
            deps:
                - 'jquery'
        'jquery.jstree':
            deps:
                - 'jquery'
        'jstree/jquery.cookie':
            deps:
                - 'jquery.jstree'
        'jstree/jquery.hotkeys':
            deps:
                - 'jquery.jstree'
        'flotr2':
            deps:
                - 'jquery'
        'bootstrap':
            deps:
                - 'jquery'
        'underscore':
            exports: '_'
        'backbone':
            deps:
                - 'jquery'
                - 'underscore'
            exports: 'Backbone'
        'backbone/bootstrap-modal':
            deps:
                - 'jquery'
                - 'underscore'
                - 'backbone'
        'jquery.ajax.queue':
            deps:
                - 'jquery'
    map:
        '*':
            'jquery': 'oroui/js/jquery-extend'
            'jquery.select2': 'oroui/js/select2-extend'
            'jquery-ui': 'oroui/js/jquery-ui-datepicker-l10n'
            'jquery-ui-timepicker': 'oroui/js/jquery-ui-timepicker-l10n'
        'oroui/js/jquery-extend':
            'jquery': 'jquery'
        'oroui/js/select2-extend':
            'jquery.select2': 'jquery.select2'
        'oroui/js/jquery-ui-extend':
            'jquery-ui': 'jquery-ui'
        'oroui/js/jquery-ui-datepicker-l10n':
            'jquery-ui': 'oroui/js/jquery-ui-extend'
        'oroui/js/jquery-ui-timepicker-l10n':
            'jquery-ui-timepicker': 'jquery-ui-timepicker'
    paths:
        'text': 'bundles/oroui/lib/text.js'
        'json': 'bundles/oroui/lib/json2.js'
        'base64': 'bundles/oroui/lib/base64.js'
        'jquery': 'bundles/oroui/lib/jquery-2.0.2.js'
        'jquery-ui': 'bundles/oroui/lib/jquery-ui-1.10.4.js'
        'jquery-ui-timepicker': 'bundles/oroui/lib/jquery-ui-timepicker-addon.js'
        'jquery-outer-html': 'bundles/oroui/lib/outerHTML-2.1.0-min.js'
        'jquery.mousewheel': 'bundles/oroui/lib/jquery/jquery.mousewheel.min.js'
        'jquery.numeric': 'bundles/oroui/lib/jquery/jquery.numeric.js'
        'jquery.uniform': 'bundles/oroui/lib/jquery/jquery.uniform.min.js'
        'jquery.select2': 'bundles/oroui/lib/jquery/select2.js'
        'jquery.jstree': 'bundles/oroui/lib/jstree/jquery.jstree.js'
        'jquery.ajax.queue': 'bundles/oroui/lib/jquery/jquery.ajaxQueue.min.js'
        'jstree/jquery.cookie': 'bundles/oroui/lib/jstree/jquery.cookie.js'
        'jstree/jquery.hotkeys': 'bundles/oroui/lib/jstree/jquery.hotkeys.js'
        'flotr2': 'bundles/oroui/lib/flotr2/flotr2.amd.js'
        'bean': 'bundles/oroui/lib/flotr2/bean.js'
        'bootstrap': 'bundles/oroui/lib/bootstrap.min.js'
        'underscore': 'bundles/oroui/lib/underscore.js'
        'backbone': 'bundles/oroui/lib/backbone.js'
        'backbone/bootstrap-modal': 'bundles/oroui/lib/backbone.bootstrap-modal.js'

        'oroui/js/app': 'bundles/oroui/js/app.js'
        'oroui/js/delete-confirmation': 'bundles/oroui/js/delete-confirmation.js'
        'oroui/js/error': 'bundles/oroui/js/error.js'
        'oroui/js/init-layout': 'bundles/oroui/js/init-layout.js'
        'oroui/js/jquery-extend': 'bundles/oroui/js/jquery-extend.js'
        'oroui/js/jquery-ui-datepicker-l10n': 'bundles/oroui/js/jquery-ui-datepicker-l10n.js'
        'oroui/js/jquery-ui-timepicker-l10n': 'bundles/oroui/js/jquery-ui-timepicker-l10n.js'
        'oroui/js/layout': 'bundles/oroui/js/layout.js'
        'oroui/js/loading-mask': 'bundles/oroui/js/loading-mask.js'
        'oroui/js/mediator': 'bundles/oroui/js/mediator.js'
        'oroui/js/messenger': 'bundles/oroui/js/messenger.js'
        'oroui/js/modal': 'bundles/oroui/js/modal.js'
        'oroui/js/scrollspy': 'bundles/oroui/js/scrollspy.js'
        'oroui/js/tools': 'bundles/oroui/js/tools.js'
        'oroui/js/widget-control-initializer': 'bundles/oroui/js/widget-control-initializer.js'
        'oroui/js/widget-manager': 'bundles/oroui/js/widget-manager.js'
        'oroui/js/widget/abstract': 'bundles/oroui/js/widget/abstract.js'
        'oro/block-widget': 'bundles/oroui/js/widget/block.js'
        'oro/page-widget': 'bundles/oroui/js/widget/page.js'
        'oro/buttons-widget': 'bundles/oroui/js/widget/buttons.js'
        'oroui/js/mobile/layout': 'bundles/oroui/js/mobile/layout.js'
        'oroui/js/mobile/page-header': 'bundles/oroui/js/mobile/page-header.js'
        'oroui/js/mobile/side-menu': 'bundles/oroui/js/mobile/side-menu.js'

        'oroui/js/items-manager/table': 'bundles/oroui/js/items-manager/table.js'
        'oroui/js/items-manager/editor': 'bundles/oroui/js/items-manager/editor.js'

        'oroui/js/content-processor/pinned-dropdown-button': 'oroui/js/content-processor/pinned-dropdown-button.js'
        'oroui/js/flotr2/funnel': 'bundles/oroui/js/flotr2/funnel.js'
