parameters:
    oro_ui.placeholder.provider.class:                     Oro\Bundle\UIBundle\Placeholder\PlaceholderProvider
    oro_ui.placeholder.filter.sorter.class:                Oro\Bundle\UIBundle\Placeholder\Filter\Sorter
    oro_ui.placeholder.filter.attribute_instance_of.class: Oro\Bundle\UIBundle\Placeholder\Filter\AttributeInstanceOf
    
    oro_ui.router.class:                                   Oro\Bundle\UIBundle\Route\Router
    oro_ui.view.listener.class:                            Oro\Bundle\UIBundle\EventListener\TemplateListener
    oro_ui.format_converter.date_time.jquery_ui.class:     Oro\Bundle\UIBundle\Converter\JqueryUiDateTimeFormatConverter

services:
    # Placeholder services
    oro_ui.placeholder.provider:
        class: %oro_ui.placeholder.provider.class%
        arguments:
            - %oro_ui.placeholders%
            - []

    oro_ui.placeholder.filter.sorter:
        class: %oro_ui.placeholder.filter.sorter.class%
        tags:
            - { name: oro_ui_placeholder.filter }

    oro_ui.placeholder.filter.attribute_instance_of:
        class: %oro_ui.placeholder.filter.attribute_instance_of.class%
        arguments:
            - @service_container
        tags:
            - { name: oro_ui_placeholder.filter }

    # Other services
    oro_ui.router:
        class: %oro_ui.router.class%
        scope: request
        arguments: [@request, @router, @oro_security.security_facade]

    oro_ui.view.listener:
        class: %oro_ui.view.listener.class%
        arguments:
            - @service_container
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }

    oro_ui.format_converter.date_time.jquery_ui:
        class: %oro_ui.format_converter.date_time.jquery_ui.class%
        arguments:
            - @oro_locale.formatter.date_time
        tags:
            - { name: oro_locale.format_converter.date_time, alias: jquery_ui }
