parameters:
    oro_ui.twig.ceil.class:              Oro\Bundle\UIBundle\Twig\CeilExtension

services:
    oro_ui.twig.ceil_extension:
        class: %oro_ui.twig.ceil.class%
        tags:
            - { name: twig.extension }
