oro_system_configuration:
    groups:
        navbar_settings:
            title: oro.ui.system_configuration.groups.navbar_settings.title

    fields:
        oro_ui.navbar_position:
            type: choice
            options:
                label: 'Position'
                choices:
                    top: Top
                    left: Left

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            look_and_feel:
                                children:
                                    navbar_settings:
                                        children:
                                            - oro_ui.navbar_position
