oro_system_configuration:
    groups:
        application_settings:
            icon:        icon-desktop
            title:       'Application Settings'
            page_reload: true

        application_name_settings:
            title: 'URL'

        navbar_settings:
            title: oro.ui.system_configuration.groups.navbar_settings.title

    fields:
        oro_ui.application_url:
            type: text
            options:
                label: 'Application URL'

        oro_ui.navbar_position:
            type: choice
            options:
                label: 'Position'
                choices:
                    top: Top
                    left: Left

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            application_settings:
                                priority: 260
                                children:
                                    application_name_settings:
                                        children:
                                            - oro_ui.application_url
                            look_and_feel:
                                children:
                                    navbar_settings:
                                        children:
                                            - oro_ui.navbar_position
