oro_system_configuration:
    groups:
        application_settings:
            icon:   icon-desktop
            title:  'Application Settings'
        application_name_settings:
            title:  'Name'
        navbar_settings:
            title:       'Navigation bar'
            description: 'Reload the page for settings to take effect'
    fields:
        oro_ui.application_name:
            type: text
            options:
                label: 'Short Name'
        oro_ui.application_title:
            type: text
            options:
                label: 'Full Name'
        oro_ui.navbar_position:
            type: choice
            options:
                label: 'Position'
                choices:
                    top: Top
                    left: Left
                    right: Right
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            application_settings:
                                priority: 260
                                children:
                                    application_name_settings:
                                        children:
                                            - oro_ui.application_name
                                            - oro_ui.application_title
                            look_and_feel:
                                children:
                                    navbar_settings:
                                        children:
                                            - oro_ui.navbar_position
