elements:
  Entity Edit Button:
    selector: 'a.edit-button'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element

  Flash Message:
    selector: '.flash-messages-holder div.alert'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element
