oro_layout:
    themes:
        base:
            # The layout theme that is used to add the page content and common page elements
            # for all themes in "main" group
            label:  ~ # this is a "hidden" theme
            groups: [ main ]

        oro:
            # Default layout theme for the Oro Platform
            label:  Oro Theme
            icon:   bundles/oroui/themes/oro/images/favicon.ico
            parent: base
            groups: [ main ]
