oro_layout:
    actions:
        - @add:
            id:        index_before_content_addition
            parentId:  before_content_addition
            blockType: placeholder
            options:
                placeholder_name: content_after
        - @addTree:
            items:
                page_header:
                    blockType: container
                page_header_left_panel:
                    blockType: container
                page_header_right_panel:
                    blockType: container
                page_title:
                    blockType: text
                page_buttons_panel:
                    blockType: container
                nav_buttons:
                    blockType: container
                index_navButtons_before_placeholder:
                    blockType: placeholder
                    options:
                        placeholder_name: index_navButtons_before
                        placeholder_parameters:
                            entity_class: { @value: $context.entity_class }
                index_navButtons_after_placeholder:
                    blockType: placeholder
                    options:
                        placeholder_name: index_navButtons_after
                        placeholder_parameters:
                            entity_class: { @value: $context.entity_class }
            tree:
                content:
                    page_header:
                        page_header_left_panel:
                            page_title: ~
                        page_buttons_panel:
                            index_navButtons_before_placeholder: ~
                            nav_buttons: ~
                            index_navButtons_after_placeholder: ~
