oro_layout:
    actions:
        - @add:
            id:        before_content_addition_placeholder
            parentId:  before_content_addition
            blockType: placeholder
            options:
                placeholder_name: index_before_content_addition
        - @addTree:
            items:
                page_header_panel:
                    blockType: container
                page_header:
                    blockType: container
                page_header_left_panel:
                    blockType: container
                page_header_right_panel:
                    blockType: container
                page_title_panel:
                    blockType: breadcrumbs
                page_title:
                    blockType: text
                page_buttons_panel:
                    blockType: container
                nav_buttons:
                    blockType: container
                nav_buttons_before:
                    blockType: placeholder
                    options:
                        placeholder_name: index_navButtons_before
                        placeholder_parameters:
                            entity_class: { @value: $context.entity_class }
                nav_buttons_after:
                    blockType: placeholder
                    options:
                        placeholder_name: index_navButtons_after
                        placeholder_parameters:
                            entity_class: { @value: $context.entity_class }
                page_content:
                    blockType: container
            tree:
                content:
                    page_header_panel:
                        page_header:
                            page_header_left_panel:
                                page_title_panel: ~
                            page_buttons_panel:
                                nav_buttons_before: ~
                                nav_buttons: ~
                                nav_buttons_after: ~
                    page_content: ~
