styles:
    inputs:
        - 'bundles/oroui/lib/font-awesome/css/font-awesome.css'
        - 'bundles/oroui/lib/multiselect/jquery.multiselect.css'
        - 'bundles/oroui/lib/multiselect/jquery.multiselect.filter.css'
        - 'bundles/oroui/css/mcustomscrollbar/jquery.mCustomScrollbar.css'
        - 'bundles/oroui/css/mcustomscrollbar/customize/jquery.mCustomScrollbar.css'
        - 'bundles/oroui/css/jquery-ui.grid.css'
        - 'bundles/oroui/css/jquery-ui.custom.css'
        - 'bundles/oroui/css/less/uniform.less'
        - 'bundles/oroui/css/less/font-awesome.less'
        - 'bundles/oroui/css/less/base.less'
        - 'bundles/oroui/css/less/desktop/form.less'
    filters: ['cssrewrite', 'cssmin']
    output: 'css/layout/base/styles.css'
